#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTruyenTranh.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WebDocTruyen")]
	public partial class QLTruyenDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAnhChap(AnhChap instance);
    partial void UpdateAnhChap(AnhChap instance);
    partial void DeleteAnhChap(AnhChap instance);
    partial void InsertTruyenTheoDoi(TruyenTheoDoi instance);
    partial void UpdateTruyenTheoDoi(TruyenTheoDoi instance);
    partial void DeleteTruyenTheoDoi(TruyenTheoDoi instance);
    partial void InsertBinhLuan(BinhLuan instance);
    partial void UpdateBinhLuan(BinhLuan instance);
    partial void DeleteBinhLuan(BinhLuan instance);
    partial void InsertChap(Chap instance);
    partial void UpdateChap(Chap instance);
    partial void DeleteChap(Chap instance);
    partial void InsertDANHGIA(DANHGIA instance);
    partial void UpdateDANHGIA(DANHGIA instance);
    partial void DeleteDANHGIA(DANHGIA instance);
    partial void InsertLichSuDoc(LichSuDoc instance);
    partial void UpdateLichSuDoc(LichSuDoc instance);
    partial void DeleteLichSuDoc(LichSuDoc instance);
    partial void InsertTacGia(TacGia instance);
    partial void UpdateTacGia(TacGia instance);
    partial void DeleteTacGia(TacGia instance);
    partial void InsertTaikhoan(Taikhoan instance);
    partial void UpdateTaikhoan(Taikhoan instance);
    partial void DeleteTaikhoan(Taikhoan instance);
    partial void InsertTheLoai(TheLoai instance);
    partial void UpdateTheLoai(TheLoai instance);
    partial void DeleteTheLoai(TheLoai instance);
    partial void InsertTruyen(Truyen instance);
    partial void UpdateTruyen(Truyen instance);
    partial void DeleteTruyen(Truyen instance);
    partial void InsertTruyen_TheLoai(Truyen_TheLoai instance);
    partial void UpdateTruyen_TheLoai(Truyen_TheLoai instance);
    partial void DeleteTruyen_TheLoai(Truyen_TheLoai instance);
    #endregion
		
		public QLTruyenDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["WebDocTruyenConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLTruyenDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLTruyenDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLTruyenDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLTruyenDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AnhChap> AnhChaps
		{
			get
			{
				return this.GetTable<AnhChap>();
			}
		}
		
		public System.Data.Linq.Table<TruyenTheoDoi> TruyenTheoDois
		{
			get
			{
				return this.GetTable<TruyenTheoDoi>();
			}
		}
		
		public System.Data.Linq.Table<BinhLuan> BinhLuans
		{
			get
			{
				return this.GetTable<BinhLuan>();
			}
		}
		
		public System.Data.Linq.Table<Chap> Chaps
		{
			get
			{
				return this.GetTable<Chap>();
			}
		}
		
		public System.Data.Linq.Table<DANHGIA> DANHGIAs
		{
			get
			{
				return this.GetTable<DANHGIA>();
			}
		}
		
		public System.Data.Linq.Table<LichSuDoc> LichSuDocs
		{
			get
			{
				return this.GetTable<LichSuDoc>();
			}
		}
		
		public System.Data.Linq.Table<TacGia> TacGias
		{
			get
			{
				return this.GetTable<TacGia>();
			}
		}
		
		public System.Data.Linq.Table<Taikhoan> Taikhoans
		{
			get
			{
				return this.GetTable<Taikhoan>();
			}
		}
		
		public System.Data.Linq.Table<TheLoai> TheLoais
		{
			get
			{
				return this.GetTable<TheLoai>();
			}
		}
		
		public System.Data.Linq.Table<Truyen> Truyens
		{
			get
			{
				return this.GetTable<Truyen>();
			}
		}
		
		public System.Data.Linq.Table<Truyen_TheLoai> Truyen_TheLoais
		{
			get
			{
				return this.GetTable<Truyen_TheLoai>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AnhChap")]
	public partial class AnhChap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDAnh;
		
		private System.Nullable<int> _ChapID;
		
		private string _LinkAnh;
		
		private System.Nullable<int> _SoTrang;
		
		private EntityRef<Chap> _Chap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDAnhChanging(int value);
    partial void OnIDAnhChanged();
    partial void OnChapIDChanging(System.Nullable<int> value);
    partial void OnChapIDChanged();
    partial void OnLinkAnhChanging(string value);
    partial void OnLinkAnhChanged();
    partial void OnSoTrangChanging(System.Nullable<int> value);
    partial void OnSoTrangChanged();
    #endregion
		
		public AnhChap()
		{
			this._Chap = default(EntityRef<Chap>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDAnh", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDAnh
		{
			get
			{
				return this._IDAnh;
			}
			set
			{
				if ((this._IDAnh != value))
				{
					this.OnIDAnhChanging(value);
					this.SendPropertyChanging();
					this._IDAnh = value;
					this.SendPropertyChanged("IDAnh");
					this.OnIDAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChapID", DbType="Int")]
		public System.Nullable<int> ChapID
		{
			get
			{
				return this._ChapID;
			}
			set
			{
				if ((this._ChapID != value))
				{
					if (this._Chap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnChapIDChanging(value);
					this.SendPropertyChanging();
					this._ChapID = value;
					this.SendPropertyChanged("ChapID");
					this.OnChapIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkAnh", DbType="VarChar(100)")]
		public string LinkAnh
		{
			get
			{
				return this._LinkAnh;
			}
			set
			{
				if ((this._LinkAnh != value))
				{
					this.OnLinkAnhChanging(value);
					this.SendPropertyChanging();
					this._LinkAnh = value;
					this.SendPropertyChanged("LinkAnh");
					this.OnLinkAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTrang", DbType="Int")]
		public System.Nullable<int> SoTrang
		{
			get
			{
				return this._SoTrang;
			}
			set
			{
				if ((this._SoTrang != value))
				{
					this.OnSoTrangChanging(value);
					this.SendPropertyChanging();
					this._SoTrang = value;
					this.SendPropertyChanged("SoTrang");
					this.OnSoTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Chap_AnhChap", Storage="_Chap", ThisKey="ChapID", OtherKey="ChapID", IsForeignKey=true)]
		public Chap Chap
		{
			get
			{
				return this._Chap.Entity;
			}
			set
			{
				Chap previousValue = this._Chap.Entity;
				if (((previousValue != value) 
							|| (this._Chap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Chap.Entity = null;
						previousValue.AnhChaps.Remove(this);
					}
					this._Chap.Entity = value;
					if ((value != null))
					{
						value.AnhChaps.Add(this);
						this._ChapID = value.ChapID;
					}
					else
					{
						this._ChapID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Chap");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TruyenTheoDoi")]
	public partial class TruyenTheoDoi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDNguoiDung;
		
		private int _TruyenID;
		
		private System.Nullable<System.DateTime> _NgayTheoDoi;
		
		private EntityRef<Taikhoan> _Taikhoan;
		
		private EntityRef<Truyen> _Truyen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDNguoiDungChanging(int value);
    partial void OnIDNguoiDungChanged();
    partial void OnTruyenIDChanging(int value);
    partial void OnTruyenIDChanged();
    partial void OnNgayTheoDoiChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTheoDoiChanged();
    #endregion
		
		public TruyenTheoDoi()
		{
			this._Taikhoan = default(EntityRef<Taikhoan>);
			this._Truyen = default(EntityRef<Truyen>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNguoiDung", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDNguoiDung
		{
			get
			{
				return this._IDNguoiDung;
			}
			set
			{
				if ((this._IDNguoiDung != value))
				{
					if (this._Taikhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._IDNguoiDung = value;
					this.SendPropertyChanged("IDNguoiDung");
					this.OnIDNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruyenID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TruyenID
		{
			get
			{
				return this._TruyenID;
			}
			set
			{
				if ((this._TruyenID != value))
				{
					if (this._Truyen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTruyenIDChanging(value);
					this.SendPropertyChanging();
					this._TruyenID = value;
					this.SendPropertyChanged("TruyenID");
					this.OnTruyenIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTheoDoi", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayTheoDoi
		{
			get
			{
				return this._NgayTheoDoi;
			}
			set
			{
				if ((this._NgayTheoDoi != value))
				{
					this.OnNgayTheoDoiChanging(value);
					this.SendPropertyChanging();
					this._NgayTheoDoi = value;
					this.SendPropertyChanged("NgayTheoDoi");
					this.OnNgayTheoDoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Taikhoan_TruyenTheoDoi", Storage="_Taikhoan", ThisKey="IDNguoiDung", OtherKey="IDNguoiDung", IsForeignKey=true)]
		public Taikhoan Taikhoan
		{
			get
			{
				return this._Taikhoan.Entity;
			}
			set
			{
				Taikhoan previousValue = this._Taikhoan.Entity;
				if (((previousValue != value) 
							|| (this._Taikhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Taikhoan.Entity = null;
						previousValue.TruyenTheoDois.Remove(this);
					}
					this._Taikhoan.Entity = value;
					if ((value != null))
					{
						value.TruyenTheoDois.Add(this);
						this._IDNguoiDung = value.IDNguoiDung;
					}
					else
					{
						this._IDNguoiDung = default(int);
					}
					this.SendPropertyChanged("Taikhoan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Truyen_TruyenTheoDoi", Storage="_Truyen", ThisKey="TruyenID", OtherKey="TruyenID", IsForeignKey=true)]
		public Truyen Truyen
		{
			get
			{
				return this._Truyen.Entity;
			}
			set
			{
				Truyen previousValue = this._Truyen.Entity;
				if (((previousValue != value) 
							|| (this._Truyen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Truyen.Entity = null;
						previousValue.TruyenTheoDois.Remove(this);
					}
					this._Truyen.Entity = value;
					if ((value != null))
					{
						value.TruyenTheoDois.Add(this);
						this._TruyenID = value.TruyenID;
					}
					else
					{
						this._TruyenID = default(int);
					}
					this.SendPropertyChanged("Truyen");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BinhLuan")]
	public partial class BinhLuan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _BinhLuanID;
		
		private string _NoiDung;
		
		private System.Nullable<System.DateTime> _NgayDang;
		
		private System.Nullable<int> _IDNguoiDung;
		
		private System.Nullable<int> _IDChap;
		
		private System.Nullable<int> _IDTruyen;
		
		private EntityRef<Chap> _Chap;
		
		private EntityRef<Taikhoan> _Taikhoan;
		
		private EntityRef<Truyen> _Truyen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBinhLuanIDChanging(int value);
    partial void OnBinhLuanIDChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnNgayDangChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDangChanged();
    partial void OnIDNguoiDungChanging(System.Nullable<int> value);
    partial void OnIDNguoiDungChanged();
    partial void OnIDChapChanging(System.Nullable<int> value);
    partial void OnIDChapChanged();
    partial void OnIDTruyenChanging(System.Nullable<int> value);
    partial void OnIDTruyenChanged();
    #endregion
		
		public BinhLuan()
		{
			this._Chap = default(EntityRef<Chap>);
			this._Taikhoan = default(EntityRef<Taikhoan>);
			this._Truyen = default(EntityRef<Truyen>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BinhLuanID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int BinhLuanID
		{
			get
			{
				return this._BinhLuanID;
			}
			set
			{
				if ((this._BinhLuanID != value))
				{
					this.OnBinhLuanIDChanging(value);
					this.SendPropertyChanging();
					this._BinhLuanID = value;
					this.SendPropertyChanged("BinhLuanID");
					this.OnBinhLuanIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDang", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayDang
		{
			get
			{
				return this._NgayDang;
			}
			set
			{
				if ((this._NgayDang != value))
				{
					this.OnNgayDangChanging(value);
					this.SendPropertyChanging();
					this._NgayDang = value;
					this.SendPropertyChanged("NgayDang");
					this.OnNgayDangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNguoiDung", DbType="Int")]
		public System.Nullable<int> IDNguoiDung
		{
			get
			{
				return this._IDNguoiDung;
			}
			set
			{
				if ((this._IDNguoiDung != value))
				{
					if (this._Taikhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._IDNguoiDung = value;
					this.SendPropertyChanged("IDNguoiDung");
					this.OnIDNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDChap", DbType="Int")]
		public System.Nullable<int> IDChap
		{
			get
			{
				return this._IDChap;
			}
			set
			{
				if ((this._IDChap != value))
				{
					if (this._Chap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDChapChanging(value);
					this.SendPropertyChanging();
					this._IDChap = value;
					this.SendPropertyChanged("IDChap");
					this.OnIDChapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTruyen", DbType="Int")]
		public System.Nullable<int> IDTruyen
		{
			get
			{
				return this._IDTruyen;
			}
			set
			{
				if ((this._IDTruyen != value))
				{
					if (this._Truyen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDTruyenChanging(value);
					this.SendPropertyChanging();
					this._IDTruyen = value;
					this.SendPropertyChanged("IDTruyen");
					this.OnIDTruyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Chap_BinhLuan", Storage="_Chap", ThisKey="IDChap", OtherKey="ChapID", IsForeignKey=true)]
		public Chap Chap
		{
			get
			{
				return this._Chap.Entity;
			}
			set
			{
				Chap previousValue = this._Chap.Entity;
				if (((previousValue != value) 
							|| (this._Chap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Chap.Entity = null;
						previousValue.BinhLuans.Remove(this);
					}
					this._Chap.Entity = value;
					if ((value != null))
					{
						value.BinhLuans.Add(this);
						this._IDChap = value.ChapID;
					}
					else
					{
						this._IDChap = default(Nullable<int>);
					}
					this.SendPropertyChanged("Chap");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Taikhoan_BinhLuan", Storage="_Taikhoan", ThisKey="IDNguoiDung", OtherKey="IDNguoiDung", IsForeignKey=true)]
		public Taikhoan Taikhoan
		{
			get
			{
				return this._Taikhoan.Entity;
			}
			set
			{
				Taikhoan previousValue = this._Taikhoan.Entity;
				if (((previousValue != value) 
							|| (this._Taikhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Taikhoan.Entity = null;
						previousValue.BinhLuans.Remove(this);
					}
					this._Taikhoan.Entity = value;
					if ((value != null))
					{
						value.BinhLuans.Add(this);
						this._IDNguoiDung = value.IDNguoiDung;
					}
					else
					{
						this._IDNguoiDung = default(Nullable<int>);
					}
					this.SendPropertyChanged("Taikhoan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Truyen_BinhLuan", Storage="_Truyen", ThisKey="IDTruyen", OtherKey="TruyenID", IsForeignKey=true)]
		public Truyen Truyen
		{
			get
			{
				return this._Truyen.Entity;
			}
			set
			{
				Truyen previousValue = this._Truyen.Entity;
				if (((previousValue != value) 
							|| (this._Truyen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Truyen.Entity = null;
						previousValue.BinhLuans.Remove(this);
					}
					this._Truyen.Entity = value;
					if ((value != null))
					{
						value.BinhLuans.Add(this);
						this._IDTruyen = value.TruyenID;
					}
					else
					{
						this._IDTruyen = default(Nullable<int>);
					}
					this.SendPropertyChanged("Truyen");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Chap")]
	public partial class Chap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ChapID;
		
		private string _TieuDe;
		
		private int _SoChap;
		
		private System.Nullable<System.DateTime> _NgayDang;
		
		private int _TruyenID;
		
		private EntitySet<AnhChap> _AnhChaps;
		
		private EntitySet<BinhLuan> _BinhLuans;
		
		private EntitySet<LichSuDoc> _LichSuDocs;
		
		private EntityRef<Truyen> _Truyen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnChapIDChanging(int value);
    partial void OnChapIDChanged();
    partial void OnTieuDeChanging(string value);
    partial void OnTieuDeChanged();
    partial void OnSoChapChanging(int value);
    partial void OnSoChapChanged();
    partial void OnNgayDangChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDangChanged();
    partial void OnTruyenIDChanging(int value);
    partial void OnTruyenIDChanged();
    #endregion
		
		public Chap()
		{
			this._AnhChaps = new EntitySet<AnhChap>(new Action<AnhChap>(this.attach_AnhChaps), new Action<AnhChap>(this.detach_AnhChaps));
			this._BinhLuans = new EntitySet<BinhLuan>(new Action<BinhLuan>(this.attach_BinhLuans), new Action<BinhLuan>(this.detach_BinhLuans));
			this._LichSuDocs = new EntitySet<LichSuDoc>(new Action<LichSuDoc>(this.attach_LichSuDocs), new Action<LichSuDoc>(this.detach_LichSuDocs));
			this._Truyen = default(EntityRef<Truyen>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChapID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ChapID
		{
			get
			{
				return this._ChapID;
			}
			set
			{
				if ((this._ChapID != value))
				{
					this.OnChapIDChanging(value);
					this.SendPropertyChanging();
					this._ChapID = value;
					this.SendPropertyChanged("ChapID");
					this.OnChapIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDe", DbType="NVarChar(200)")]
		public string TieuDe
		{
			get
			{
				return this._TieuDe;
			}
			set
			{
				if ((this._TieuDe != value))
				{
					this.OnTieuDeChanging(value);
					this.SendPropertyChanging();
					this._TieuDe = value;
					this.SendPropertyChanged("TieuDe");
					this.OnTieuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoChap", DbType="Int NOT NULL")]
		public int SoChap
		{
			get
			{
				return this._SoChap;
			}
			set
			{
				if ((this._SoChap != value))
				{
					this.OnSoChapChanging(value);
					this.SendPropertyChanging();
					this._SoChap = value;
					this.SendPropertyChanged("SoChap");
					this.OnSoChapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDang", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayDang
		{
			get
			{
				return this._NgayDang;
			}
			set
			{
				if ((this._NgayDang != value))
				{
					this.OnNgayDangChanging(value);
					this.SendPropertyChanging();
					this._NgayDang = value;
					this.SendPropertyChanged("NgayDang");
					this.OnNgayDangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruyenID", DbType="Int NOT NULL")]
		public int TruyenID
		{
			get
			{
				return this._TruyenID;
			}
			set
			{
				if ((this._TruyenID != value))
				{
					if (this._Truyen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTruyenIDChanging(value);
					this.SendPropertyChanging();
					this._TruyenID = value;
					this.SendPropertyChanged("TruyenID");
					this.OnTruyenIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Chap_AnhChap", Storage="_AnhChaps", ThisKey="ChapID", OtherKey="ChapID")]
		public EntitySet<AnhChap> AnhChaps
		{
			get
			{
				return this._AnhChaps;
			}
			set
			{
				this._AnhChaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Chap_BinhLuan", Storage="_BinhLuans", ThisKey="ChapID", OtherKey="IDChap")]
		public EntitySet<BinhLuan> BinhLuans
		{
			get
			{
				return this._BinhLuans;
			}
			set
			{
				this._BinhLuans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Chap_LichSuDoc", Storage="_LichSuDocs", ThisKey="ChapID", OtherKey="ChapID")]
		public EntitySet<LichSuDoc> LichSuDocs
		{
			get
			{
				return this._LichSuDocs;
			}
			set
			{
				this._LichSuDocs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Truyen_Chap", Storage="_Truyen", ThisKey="TruyenID", OtherKey="TruyenID", IsForeignKey=true)]
		public Truyen Truyen
		{
			get
			{
				return this._Truyen.Entity;
			}
			set
			{
				Truyen previousValue = this._Truyen.Entity;
				if (((previousValue != value) 
							|| (this._Truyen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Truyen.Entity = null;
						previousValue.Chaps.Remove(this);
					}
					this._Truyen.Entity = value;
					if ((value != null))
					{
						value.Chaps.Add(this);
						this._TruyenID = value.TruyenID;
					}
					else
					{
						this._TruyenID = default(int);
					}
					this.SendPropertyChanged("Truyen");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_AnhChaps(AnhChap entity)
		{
			this.SendPropertyChanging();
			entity.Chap = this;
		}
		
		private void detach_AnhChaps(AnhChap entity)
		{
			this.SendPropertyChanging();
			entity.Chap = null;
		}
		
		private void attach_BinhLuans(BinhLuan entity)
		{
			this.SendPropertyChanging();
			entity.Chap = this;
		}
		
		private void detach_BinhLuans(BinhLuan entity)
		{
			this.SendPropertyChanging();
			entity.Chap = null;
		}
		
		private void attach_LichSuDocs(LichSuDoc entity)
		{
			this.SendPropertyChanging();
			entity.Chap = this;
		}
		
		private void detach_LichSuDocs(LichSuDoc entity)
		{
			this.SendPropertyChanging();
			entity.Chap = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DANHGIA")]
	public partial class DANHGIA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDDANHGIA;
		
		private System.Nullable<int> _SOSAO;
		
		private System.Nullable<System.DateTime> _NGAYDANHGIA;
		
		private System.Nullable<int> _IDNguoidung;
		
		private System.Nullable<int> _TruyenID;
		
		private EntityRef<Taikhoan> _Taikhoan;
		
		private EntityRef<Truyen> _Truyen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDDANHGIAChanging(int value);
    partial void OnIDDANHGIAChanged();
    partial void OnSOSAOChanging(System.Nullable<int> value);
    partial void OnSOSAOChanged();
    partial void OnNGAYDANHGIAChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYDANHGIAChanged();
    partial void OnIDNguoidungChanging(System.Nullable<int> value);
    partial void OnIDNguoidungChanged();
    partial void OnTruyenIDChanging(System.Nullable<int> value);
    partial void OnTruyenIDChanged();
    #endregion
		
		public DANHGIA()
		{
			this._Taikhoan = default(EntityRef<Taikhoan>);
			this._Truyen = default(EntityRef<Truyen>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDANHGIA", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDDANHGIA
		{
			get
			{
				return this._IDDANHGIA;
			}
			set
			{
				if ((this._IDDANHGIA != value))
				{
					this.OnIDDANHGIAChanging(value);
					this.SendPropertyChanging();
					this._IDDANHGIA = value;
					this.SendPropertyChanged("IDDANHGIA");
					this.OnIDDANHGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOSAO", DbType="Int")]
		public System.Nullable<int> SOSAO
		{
			get
			{
				return this._SOSAO;
			}
			set
			{
				if ((this._SOSAO != value))
				{
					this.OnSOSAOChanging(value);
					this.SendPropertyChanging();
					this._SOSAO = value;
					this.SendPropertyChanged("SOSAO");
					this.OnSOSAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYDANHGIA", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYDANHGIA
		{
			get
			{
				return this._NGAYDANHGIA;
			}
			set
			{
				if ((this._NGAYDANHGIA != value))
				{
					this.OnNGAYDANHGIAChanging(value);
					this.SendPropertyChanging();
					this._NGAYDANHGIA = value;
					this.SendPropertyChanged("NGAYDANHGIA");
					this.OnNGAYDANHGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNguoidung", DbType="Int")]
		public System.Nullable<int> IDNguoidung
		{
			get
			{
				return this._IDNguoidung;
			}
			set
			{
				if ((this._IDNguoidung != value))
				{
					if (this._Taikhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDNguoidungChanging(value);
					this.SendPropertyChanging();
					this._IDNguoidung = value;
					this.SendPropertyChanged("IDNguoidung");
					this.OnIDNguoidungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruyenID", DbType="Int")]
		public System.Nullable<int> TruyenID
		{
			get
			{
				return this._TruyenID;
			}
			set
			{
				if ((this._TruyenID != value))
				{
					if (this._Truyen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTruyenIDChanging(value);
					this.SendPropertyChanging();
					this._TruyenID = value;
					this.SendPropertyChanged("TruyenID");
					this.OnTruyenIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Taikhoan_DANHGIA", Storage="_Taikhoan", ThisKey="IDNguoidung", OtherKey="IDNguoiDung", IsForeignKey=true)]
		public Taikhoan Taikhoan
		{
			get
			{
				return this._Taikhoan.Entity;
			}
			set
			{
				Taikhoan previousValue = this._Taikhoan.Entity;
				if (((previousValue != value) 
							|| (this._Taikhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Taikhoan.Entity = null;
						previousValue.DANHGIAs.Remove(this);
					}
					this._Taikhoan.Entity = value;
					if ((value != null))
					{
						value.DANHGIAs.Add(this);
						this._IDNguoidung = value.IDNguoiDung;
					}
					else
					{
						this._IDNguoidung = default(Nullable<int>);
					}
					this.SendPropertyChanged("Taikhoan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Truyen_DANHGIA", Storage="_Truyen", ThisKey="TruyenID", OtherKey="TruyenID", IsForeignKey=true)]
		public Truyen Truyen
		{
			get
			{
				return this._Truyen.Entity;
			}
			set
			{
				Truyen previousValue = this._Truyen.Entity;
				if (((previousValue != value) 
							|| (this._Truyen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Truyen.Entity = null;
						previousValue.DANHGIAs.Remove(this);
					}
					this._Truyen.Entity = value;
					if ((value != null))
					{
						value.DANHGIAs.Add(this);
						this._TruyenID = value.TruyenID;
					}
					else
					{
						this._TruyenID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Truyen");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LichSuDoc")]
	public partial class LichSuDoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDNguoiDung;
		
		private int _TruyenID;
		
		private int _ChapID;
		
		private System.Nullable<System.DateTime> _NgayDocCuoi;
		
		private EntityRef<Chap> _Chap;
		
		private EntityRef<Taikhoan> _Taikhoan;
		
		private EntityRef<Truyen> _Truyen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDNguoiDungChanging(int value);
    partial void OnIDNguoiDungChanged();
    partial void OnTruyenIDChanging(int value);
    partial void OnTruyenIDChanged();
    partial void OnChapIDChanging(int value);
    partial void OnChapIDChanged();
    partial void OnNgayDocCuoiChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDocCuoiChanged();
    #endregion
		
		public LichSuDoc()
		{
			this._Chap = default(EntityRef<Chap>);
			this._Taikhoan = default(EntityRef<Taikhoan>);
			this._Truyen = default(EntityRef<Truyen>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNguoiDung", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDNguoiDung
		{
			get
			{
				return this._IDNguoiDung;
			}
			set
			{
				if ((this._IDNguoiDung != value))
				{
					if (this._Taikhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._IDNguoiDung = value;
					this.SendPropertyChanged("IDNguoiDung");
					this.OnIDNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruyenID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TruyenID
		{
			get
			{
				return this._TruyenID;
			}
			set
			{
				if ((this._TruyenID != value))
				{
					if (this._Truyen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTruyenIDChanging(value);
					this.SendPropertyChanging();
					this._TruyenID = value;
					this.SendPropertyChanged("TruyenID");
					this.OnTruyenIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChapID", DbType="Int NOT NULL")]
		public int ChapID
		{
			get
			{
				return this._ChapID;
			}
			set
			{
				if ((this._ChapID != value))
				{
					if (this._Chap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnChapIDChanging(value);
					this.SendPropertyChanging();
					this._ChapID = value;
					this.SendPropertyChanged("ChapID");
					this.OnChapIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDocCuoi", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayDocCuoi
		{
			get
			{
				return this._NgayDocCuoi;
			}
			set
			{
				if ((this._NgayDocCuoi != value))
				{
					this.OnNgayDocCuoiChanging(value);
					this.SendPropertyChanging();
					this._NgayDocCuoi = value;
					this.SendPropertyChanged("NgayDocCuoi");
					this.OnNgayDocCuoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Chap_LichSuDoc", Storage="_Chap", ThisKey="ChapID", OtherKey="ChapID", IsForeignKey=true)]
		public Chap Chap
		{
			get
			{
				return this._Chap.Entity;
			}
			set
			{
				Chap previousValue = this._Chap.Entity;
				if (((previousValue != value) 
							|| (this._Chap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Chap.Entity = null;
						previousValue.LichSuDocs.Remove(this);
					}
					this._Chap.Entity = value;
					if ((value != null))
					{
						value.LichSuDocs.Add(this);
						this._ChapID = value.ChapID;
					}
					else
					{
						this._ChapID = default(int);
					}
					this.SendPropertyChanged("Chap");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Taikhoan_LichSuDoc", Storage="_Taikhoan", ThisKey="IDNguoiDung", OtherKey="IDNguoiDung", IsForeignKey=true)]
		public Taikhoan Taikhoan
		{
			get
			{
				return this._Taikhoan.Entity;
			}
			set
			{
				Taikhoan previousValue = this._Taikhoan.Entity;
				if (((previousValue != value) 
							|| (this._Taikhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Taikhoan.Entity = null;
						previousValue.LichSuDocs.Remove(this);
					}
					this._Taikhoan.Entity = value;
					if ((value != null))
					{
						value.LichSuDocs.Add(this);
						this._IDNguoiDung = value.IDNguoiDung;
					}
					else
					{
						this._IDNguoiDung = default(int);
					}
					this.SendPropertyChanged("Taikhoan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Truyen_LichSuDoc", Storage="_Truyen", ThisKey="TruyenID", OtherKey="TruyenID", IsForeignKey=true)]
		public Truyen Truyen
		{
			get
			{
				return this._Truyen.Entity;
			}
			set
			{
				Truyen previousValue = this._Truyen.Entity;
				if (((previousValue != value) 
							|| (this._Truyen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Truyen.Entity = null;
						previousValue.LichSuDocs.Remove(this);
					}
					this._Truyen.Entity = value;
					if ((value != null))
					{
						value.LichSuDocs.Add(this);
						this._TruyenID = value.TruyenID;
					}
					else
					{
						this._TruyenID = default(int);
					}
					this.SendPropertyChanged("Truyen");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TacGia")]
	public partial class TacGia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDTacGia;
		
		private string _TenTacGia;
		
		private EntitySet<Truyen> _Truyens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDTacGiaChanging(int value);
    partial void OnIDTacGiaChanged();
    partial void OnTenTacGiaChanging(string value);
    partial void OnTenTacGiaChanged();
    #endregion
		
		public TacGia()
		{
			this._Truyens = new EntitySet<Truyen>(new Action<Truyen>(this.attach_Truyens), new Action<Truyen>(this.detach_Truyens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTacGia", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDTacGia
		{
			get
			{
				return this._IDTacGia;
			}
			set
			{
				if ((this._IDTacGia != value))
				{
					this.OnIDTacGiaChanging(value);
					this.SendPropertyChanging();
					this._IDTacGia = value;
					this.SendPropertyChanged("IDTacGia");
					this.OnIDTacGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTacGia", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenTacGia
		{
			get
			{
				return this._TenTacGia;
			}
			set
			{
				if ((this._TenTacGia != value))
				{
					this.OnTenTacGiaChanging(value);
					this.SendPropertyChanging();
					this._TenTacGia = value;
					this.SendPropertyChanged("TenTacGia");
					this.OnTenTacGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TacGia_Truyen", Storage="_Truyens", ThisKey="IDTacGia", OtherKey="IDTacGia")]
		public EntitySet<Truyen> Truyens
		{
			get
			{
				return this._Truyens;
			}
			set
			{
				this._Truyens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Truyens(Truyen entity)
		{
			this.SendPropertyChanging();
			entity.TacGia = this;
		}
		
		private void detach_Truyens(Truyen entity)
		{
			this.SendPropertyChanging();
			entity.TacGia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Taikhoan")]
	public partial class Taikhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDNguoiDung;
		
		private string _TenDangNhap;
		
		private string _MatKhau;
		
		private int _VaiTro;
		
		private string _Avatar;
		
		private string _HoTen;
		
		private string _Email;
		
		private System.Nullable<System.DateTime> _NgayDangKy;
		
		private string _GioiTinh;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private System.Nullable<bool> _TrangThai;
		
		private EntitySet<TruyenTheoDoi> _TruyenTheoDois;
		
		private EntitySet<BinhLuan> _BinhLuans;
		
		private EntitySet<DANHGIA> _DANHGIAs;
		
		private EntitySet<LichSuDoc> _LichSuDocs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDNguoiDungChanging(int value);
    partial void OnIDNguoiDungChanged();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnVaiTroChanging(int value);
    partial void OnVaiTroChanged();
    partial void OnAvatarChanging(string value);
    partial void OnAvatarChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnNgayDangKyChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDangKyChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnTrangThaiChanging(System.Nullable<bool> value);
    partial void OnTrangThaiChanged();
    #endregion
		
		public Taikhoan()
		{
			this._TruyenTheoDois = new EntitySet<TruyenTheoDoi>(new Action<TruyenTheoDoi>(this.attach_TruyenTheoDois), new Action<TruyenTheoDoi>(this.detach_TruyenTheoDois));
			this._BinhLuans = new EntitySet<BinhLuan>(new Action<BinhLuan>(this.attach_BinhLuans), new Action<BinhLuan>(this.detach_BinhLuans));
			this._DANHGIAs = new EntitySet<DANHGIA>(new Action<DANHGIA>(this.attach_DANHGIAs), new Action<DANHGIA>(this.detach_DANHGIAs));
			this._LichSuDocs = new EntitySet<LichSuDoc>(new Action<LichSuDoc>(this.attach_LichSuDocs), new Action<LichSuDoc>(this.detach_LichSuDocs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNguoiDung", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDNguoiDung
		{
			get
			{
				return this._IDNguoiDung;
			}
			set
			{
				if ((this._IDNguoiDung != value))
				{
					this.OnIDNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._IDNguoiDung = value;
					this.SendPropertyChanged("IDNguoiDung");
					this.OnIDNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VaiTro", DbType="Int NOT NULL")]
		public int VaiTro
		{
			get
			{
				return this._VaiTro;
			}
			set
			{
				if ((this._VaiTro != value))
				{
					this.OnVaiTroChanging(value);
					this.SendPropertyChanging();
					this._VaiTro = value;
					this.SendPropertyChanged("VaiTro");
					this.OnVaiTroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Avatar", DbType="VarChar(100)")]
		public string Avatar
		{
			get
			{
				return this._Avatar;
			}
			set
			{
				if ((this._Avatar != value))
				{
					this.OnAvatarChanging(value);
					this.SendPropertyChanging();
					this._Avatar = value;
					this.SendPropertyChanged("Avatar");
					this.OnAvatarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(100)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(150)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDangKy", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayDangKy
		{
			get
			{
				return this._NgayDangKy;
			}
			set
			{
				if ((this._NgayDangKy != value))
				{
					this.OnNgayDangKyChanging(value);
					this.SendPropertyChanging();
					this._NgayDangKy = value;
					this.SendPropertyChanged("NgayDangKy");
					this.OnNgayDangKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(10)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Bit")]
		public System.Nullable<bool> TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Taikhoan_TruyenTheoDoi", Storage="_TruyenTheoDois", ThisKey="IDNguoiDung", OtherKey="IDNguoiDung")]
		public EntitySet<TruyenTheoDoi> TruyenTheoDois
		{
			get
			{
				return this._TruyenTheoDois;
			}
			set
			{
				this._TruyenTheoDois.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Taikhoan_BinhLuan", Storage="_BinhLuans", ThisKey="IDNguoiDung", OtherKey="IDNguoiDung")]
		public EntitySet<BinhLuan> BinhLuans
		{
			get
			{
				return this._BinhLuans;
			}
			set
			{
				this._BinhLuans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Taikhoan_DANHGIA", Storage="_DANHGIAs", ThisKey="IDNguoiDung", OtherKey="IDNguoidung")]
		public EntitySet<DANHGIA> DANHGIAs
		{
			get
			{
				return this._DANHGIAs;
			}
			set
			{
				this._DANHGIAs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Taikhoan_LichSuDoc", Storage="_LichSuDocs", ThisKey="IDNguoiDung", OtherKey="IDNguoiDung")]
		public EntitySet<LichSuDoc> LichSuDocs
		{
			get
			{
				return this._LichSuDocs;
			}
			set
			{
				this._LichSuDocs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TruyenTheoDois(TruyenTheoDoi entity)
		{
			this.SendPropertyChanging();
			entity.Taikhoan = this;
		}
		
		private void detach_TruyenTheoDois(TruyenTheoDoi entity)
		{
			this.SendPropertyChanging();
			entity.Taikhoan = null;
		}
		
		private void attach_BinhLuans(BinhLuan entity)
		{
			this.SendPropertyChanging();
			entity.Taikhoan = this;
		}
		
		private void detach_BinhLuans(BinhLuan entity)
		{
			this.SendPropertyChanging();
			entity.Taikhoan = null;
		}
		
		private void attach_DANHGIAs(DANHGIA entity)
		{
			this.SendPropertyChanging();
			entity.Taikhoan = this;
		}
		
		private void detach_DANHGIAs(DANHGIA entity)
		{
			this.SendPropertyChanging();
			entity.Taikhoan = null;
		}
		
		private void attach_LichSuDocs(LichSuDoc entity)
		{
			this.SendPropertyChanging();
			entity.Taikhoan = this;
		}
		
		private void detach_LichSuDocs(LichSuDoc entity)
		{
			this.SendPropertyChanging();
			entity.Taikhoan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TheLoai")]
	public partial class TheLoai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TheLoaiID;
		
		private string _TenTheLoai;
		
		private EntitySet<Truyen_TheLoai> _Truyen_TheLoais;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTheLoaiIDChanging(int value);
    partial void OnTheLoaiIDChanged();
    partial void OnTenTheLoaiChanging(string value);
    partial void OnTenTheLoaiChanged();
    #endregion
		
		public TheLoai()
		{
			this._Truyen_TheLoais = new EntitySet<Truyen_TheLoai>(new Action<Truyen_TheLoai>(this.attach_Truyen_TheLoais), new Action<Truyen_TheLoai>(this.detach_Truyen_TheLoais));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TheLoaiID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TheLoaiID
		{
			get
			{
				return this._TheLoaiID;
			}
			set
			{
				if ((this._TheLoaiID != value))
				{
					this.OnTheLoaiIDChanging(value);
					this.SendPropertyChanging();
					this._TheLoaiID = value;
					this.SendPropertyChanged("TheLoaiID");
					this.OnTheLoaiIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTheLoai", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenTheLoai
		{
			get
			{
				return this._TenTheLoai;
			}
			set
			{
				if ((this._TenTheLoai != value))
				{
					this.OnTenTheLoaiChanging(value);
					this.SendPropertyChanging();
					this._TenTheLoai = value;
					this.SendPropertyChanged("TenTheLoai");
					this.OnTenTheLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheLoai_Truyen_TheLoai", Storage="_Truyen_TheLoais", ThisKey="TheLoaiID", OtherKey="TheLoaiID")]
		public EntitySet<Truyen_TheLoai> Truyen_TheLoais
		{
			get
			{
				return this._Truyen_TheLoais;
			}
			set
			{
				this._Truyen_TheLoais.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Truyen_TheLoais(Truyen_TheLoai entity)
		{
			this.SendPropertyChanging();
			entity.TheLoai = this;
		}
		
		private void detach_Truyen_TheLoais(Truyen_TheLoai entity)
		{
			this.SendPropertyChanging();
			entity.TheLoai = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Truyen")]
	public partial class Truyen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TruyenID;
		
		private string _TenTruyen;
		
		private System.Nullable<int> _IDTacGia;
		
		private string _MoTa;
		
		private string _AnhBia;
		
		private System.Nullable<System.DateTime> _NgayCapNhat;
		
		private System.Nullable<int> _SOCHAP;
		
		private System.Nullable<int> _LuotXem;
		
		private string _TinhTrang;
		
		private EntitySet<TruyenTheoDoi> _TruyenTheoDois;
		
		private EntitySet<BinhLuan> _BinhLuans;
		
		private EntitySet<Chap> _Chaps;
		
		private EntitySet<DANHGIA> _DANHGIAs;
		
		private EntitySet<LichSuDoc> _LichSuDocs;
		
		private EntitySet<Truyen_TheLoai> _Truyen_TheLoais;
		
		private EntityRef<TacGia> _TacGia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTruyenIDChanging(int value);
    partial void OnTruyenIDChanged();
    partial void OnTenTruyenChanging(string value);
    partial void OnTenTruyenChanged();
    partial void OnIDTacGiaChanging(System.Nullable<int> value);
    partial void OnIDTacGiaChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnAnhBiaChanging(string value);
    partial void OnAnhBiaChanged();
    partial void OnNgayCapNhatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayCapNhatChanged();
    partial void OnSOCHAPChanging(System.Nullable<int> value);
    partial void OnSOCHAPChanged();
    partial void OnLuotXemChanging(System.Nullable<int> value);
    partial void OnLuotXemChanged();
    partial void OnTinhTrangChanging(string value);
    partial void OnTinhTrangChanged();
    #endregion
		
		public Truyen()
		{
			this._TruyenTheoDois = new EntitySet<TruyenTheoDoi>(new Action<TruyenTheoDoi>(this.attach_TruyenTheoDois), new Action<TruyenTheoDoi>(this.detach_TruyenTheoDois));
			this._BinhLuans = new EntitySet<BinhLuan>(new Action<BinhLuan>(this.attach_BinhLuans), new Action<BinhLuan>(this.detach_BinhLuans));
			this._Chaps = new EntitySet<Chap>(new Action<Chap>(this.attach_Chaps), new Action<Chap>(this.detach_Chaps));
			this._DANHGIAs = new EntitySet<DANHGIA>(new Action<DANHGIA>(this.attach_DANHGIAs), new Action<DANHGIA>(this.detach_DANHGIAs));
			this._LichSuDocs = new EntitySet<LichSuDoc>(new Action<LichSuDoc>(this.attach_LichSuDocs), new Action<LichSuDoc>(this.detach_LichSuDocs));
			this._Truyen_TheLoais = new EntitySet<Truyen_TheLoai>(new Action<Truyen_TheLoai>(this.attach_Truyen_TheLoais), new Action<Truyen_TheLoai>(this.detach_Truyen_TheLoais));
			this._TacGia = default(EntityRef<TacGia>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruyenID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TruyenID
		{
			get
			{
				return this._TruyenID;
			}
			set
			{
				if ((this._TruyenID != value))
				{
					this.OnTruyenIDChanging(value);
					this.SendPropertyChanging();
					this._TruyenID = value;
					this.SendPropertyChanged("TruyenID");
					this.OnTruyenIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTruyen", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string TenTruyen
		{
			get
			{
				return this._TenTruyen;
			}
			set
			{
				if ((this._TenTruyen != value))
				{
					this.OnTenTruyenChanging(value);
					this.SendPropertyChanging();
					this._TenTruyen = value;
					this.SendPropertyChanged("TenTruyen");
					this.OnTenTruyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTacGia", DbType="Int")]
		public System.Nullable<int> IDTacGia
		{
			get
			{
				return this._IDTacGia;
			}
			set
			{
				if ((this._IDTacGia != value))
				{
					if (this._TacGia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDTacGiaChanging(value);
					this.SendPropertyChanging();
					this._IDTacGia = value;
					this.SendPropertyChanged("IDTacGia");
					this.OnIDTacGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(MAX)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnhBia", DbType="NVarChar(255)")]
		public string AnhBia
		{
			get
			{
				return this._AnhBia;
			}
			set
			{
				if ((this._AnhBia != value))
				{
					this.OnAnhBiaChanging(value);
					this.SendPropertyChanging();
					this._AnhBia = value;
					this.SendPropertyChanged("AnhBia");
					this.OnAnhBiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCapNhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayCapNhat
		{
			get
			{
				return this._NgayCapNhat;
			}
			set
			{
				if ((this._NgayCapNhat != value))
				{
					this.OnNgayCapNhatChanging(value);
					this.SendPropertyChanging();
					this._NgayCapNhat = value;
					this.SendPropertyChanged("NgayCapNhat");
					this.OnNgayCapNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCHAP", DbType="Int")]
		public System.Nullable<int> SOCHAP
		{
			get
			{
				return this._SOCHAP;
			}
			set
			{
				if ((this._SOCHAP != value))
				{
					this.OnSOCHAPChanging(value);
					this.SendPropertyChanging();
					this._SOCHAP = value;
					this.SendPropertyChanged("SOCHAP");
					this.OnSOCHAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LuotXem", DbType="Int")]
		public System.Nullable<int> LuotXem
		{
			get
			{
				return this._LuotXem;
			}
			set
			{
				if ((this._LuotXem != value))
				{
					this.OnLuotXemChanging(value);
					this.SendPropertyChanging();
					this._LuotXem = value;
					this.SendPropertyChanged("LuotXem");
					this.OnLuotXemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="NVarChar(100)")]
		public string TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Truyen_TruyenTheoDoi", Storage="_TruyenTheoDois", ThisKey="TruyenID", OtherKey="TruyenID")]
		public EntitySet<TruyenTheoDoi> TruyenTheoDois
		{
			get
			{
				return this._TruyenTheoDois;
			}
			set
			{
				this._TruyenTheoDois.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Truyen_BinhLuan", Storage="_BinhLuans", ThisKey="TruyenID", OtherKey="IDTruyen")]
		public EntitySet<BinhLuan> BinhLuans
		{
			get
			{
				return this._BinhLuans;
			}
			set
			{
				this._BinhLuans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Truyen_Chap", Storage="_Chaps", ThisKey="TruyenID", OtherKey="TruyenID")]
		public EntitySet<Chap> Chaps
		{
			get
			{
				return this._Chaps;
			}
			set
			{
				this._Chaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Truyen_DANHGIA", Storage="_DANHGIAs", ThisKey="TruyenID", OtherKey="TruyenID")]
		public EntitySet<DANHGIA> DANHGIAs
		{
			get
			{
				return this._DANHGIAs;
			}
			set
			{
				this._DANHGIAs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Truyen_LichSuDoc", Storage="_LichSuDocs", ThisKey="TruyenID", OtherKey="TruyenID")]
		public EntitySet<LichSuDoc> LichSuDocs
		{
			get
			{
				return this._LichSuDocs;
			}
			set
			{
				this._LichSuDocs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Truyen_Truyen_TheLoai", Storage="_Truyen_TheLoais", ThisKey="TruyenID", OtherKey="TruyenID")]
		public EntitySet<Truyen_TheLoai> Truyen_TheLoais
		{
			get
			{
				return this._Truyen_TheLoais;
			}
			set
			{
				this._Truyen_TheLoais.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TacGia_Truyen", Storage="_TacGia", ThisKey="IDTacGia", OtherKey="IDTacGia", IsForeignKey=true)]
		public TacGia TacGia
		{
			get
			{
				return this._TacGia.Entity;
			}
			set
			{
				TacGia previousValue = this._TacGia.Entity;
				if (((previousValue != value) 
							|| (this._TacGia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TacGia.Entity = null;
						previousValue.Truyens.Remove(this);
					}
					this._TacGia.Entity = value;
					if ((value != null))
					{
						value.Truyens.Add(this);
						this._IDTacGia = value.IDTacGia;
					}
					else
					{
						this._IDTacGia = default(Nullable<int>);
					}
					this.SendPropertyChanged("TacGia");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TruyenTheoDois(TruyenTheoDoi entity)
		{
			this.SendPropertyChanging();
			entity.Truyen = this;
		}
		
		private void detach_TruyenTheoDois(TruyenTheoDoi entity)
		{
			this.SendPropertyChanging();
			entity.Truyen = null;
		}
		
		private void attach_BinhLuans(BinhLuan entity)
		{
			this.SendPropertyChanging();
			entity.Truyen = this;
		}
		
		private void detach_BinhLuans(BinhLuan entity)
		{
			this.SendPropertyChanging();
			entity.Truyen = null;
		}
		
		private void attach_Chaps(Chap entity)
		{
			this.SendPropertyChanging();
			entity.Truyen = this;
		}
		
		private void detach_Chaps(Chap entity)
		{
			this.SendPropertyChanging();
			entity.Truyen = null;
		}
		
		private void attach_DANHGIAs(DANHGIA entity)
		{
			this.SendPropertyChanging();
			entity.Truyen = this;
		}
		
		private void detach_DANHGIAs(DANHGIA entity)
		{
			this.SendPropertyChanging();
			entity.Truyen = null;
		}
		
		private void attach_LichSuDocs(LichSuDoc entity)
		{
			this.SendPropertyChanging();
			entity.Truyen = this;
		}
		
		private void detach_LichSuDocs(LichSuDoc entity)
		{
			this.SendPropertyChanging();
			entity.Truyen = null;
		}
		
		private void attach_Truyen_TheLoais(Truyen_TheLoai entity)
		{
			this.SendPropertyChanging();
			entity.Truyen = this;
		}
		
		private void detach_Truyen_TheLoais(Truyen_TheLoai entity)
		{
			this.SendPropertyChanging();
			entity.Truyen = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Truyen_TheLoai")]
	public partial class Truyen_TheLoai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TruyenID;
		
		private int _TheLoaiID;
		
		private EntityRef<TheLoai> _TheLoai;
		
		private EntityRef<Truyen> _Truyen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTruyenIDChanging(int value);
    partial void OnTruyenIDChanged();
    partial void OnTheLoaiIDChanging(int value);
    partial void OnTheLoaiIDChanged();
    #endregion
		
		public Truyen_TheLoai()
		{
			this._TheLoai = default(EntityRef<TheLoai>);
			this._Truyen = default(EntityRef<Truyen>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruyenID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TruyenID
		{
			get
			{
				return this._TruyenID;
			}
			set
			{
				if ((this._TruyenID != value))
				{
					if (this._Truyen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTruyenIDChanging(value);
					this.SendPropertyChanging();
					this._TruyenID = value;
					this.SendPropertyChanged("TruyenID");
					this.OnTruyenIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TheLoaiID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TheLoaiID
		{
			get
			{
				return this._TheLoaiID;
			}
			set
			{
				if ((this._TheLoaiID != value))
				{
					if (this._TheLoai.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTheLoaiIDChanging(value);
					this.SendPropertyChanging();
					this._TheLoaiID = value;
					this.SendPropertyChanged("TheLoaiID");
					this.OnTheLoaiIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheLoai_Truyen_TheLoai", Storage="_TheLoai", ThisKey="TheLoaiID", OtherKey="TheLoaiID", IsForeignKey=true)]
		public TheLoai TheLoai
		{
			get
			{
				return this._TheLoai.Entity;
			}
			set
			{
				TheLoai previousValue = this._TheLoai.Entity;
				if (((previousValue != value) 
							|| (this._TheLoai.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TheLoai.Entity = null;
						previousValue.Truyen_TheLoais.Remove(this);
					}
					this._TheLoai.Entity = value;
					if ((value != null))
					{
						value.Truyen_TheLoais.Add(this);
						this._TheLoaiID = value.TheLoaiID;
					}
					else
					{
						this._TheLoaiID = default(int);
					}
					this.SendPropertyChanged("TheLoai");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Truyen_Truyen_TheLoai", Storage="_Truyen", ThisKey="TruyenID", OtherKey="TruyenID", IsForeignKey=true)]
		public Truyen Truyen
		{
			get
			{
				return this._Truyen.Entity;
			}
			set
			{
				Truyen previousValue = this._Truyen.Entity;
				if (((previousValue != value) 
							|| (this._Truyen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Truyen.Entity = null;
						previousValue.Truyen_TheLoais.Remove(this);
					}
					this._Truyen.Entity = value;
					if ((value != null))
					{
						value.Truyen_TheLoais.Add(this);
						this._TruyenID = value.TruyenID;
					}
					else
					{
						this._TruyenID = default(int);
					}
					this.SendPropertyChanged("Truyen");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
